# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# pypy runs super slow with coverage (at least how I am
# running it), don't run pypy with coverage.  Will need
# to use the build matrix to only run pypy with no coverage
#  - "pypy"

addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - gperf

cache:
  directories:
  - $HOME/iverilog
  - $HOME/ghdl
  - $HOME/icestorm
  - $HOME/arachne-pnr
  - $HOME/yosys

before_install:
  - g++ --version
  - export PATH=$PATH:$HOME/iverilog/bin/:$HOME/yosys/
  - export PATH=$PATH:$HOME/icestorm/icepack/:$HOME/arachne-pnr/bin/
  - echo $HOME
  - ls $HOME/
  - chmod +x ./scripts/ci/install_iverilog.sh
  - ./scripts/ci/install_iverilog.sh

# command to install dependencies, always using the latest
# myhdl for the master branch
install:
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install coverage
  - pip install coveralls
  - pip install Pillow
  - pip install .

# env:
#   - RUNLONG="false"
#   - COVERAGE="true"

# the longtests still take too long with pypy
#matrix:
#  exclude:
#    - python: "pypy"
#  include:
#    - python: "pypy"
#      env: RUNLONG="true"

# run the test
script:
  - chmod +x ./scripts/ci/run_tests.sh
  - ./scripts/ci/run_tests.sh

after_success:
  - coveralls

notifications:
  email: true
